//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ServicoWCF;
using System.Collections.Generic;
using System.Linq;

namespace Dados
{
    public class Dados
    {
        public bool Inserir(Sala sala)
        {
            bdLaboratorioEntities context = new bdLaboratorioEntities();
            context.Sala.Add(sala);
            int retorno = context.SaveChanges();

            return retorno == 1;
        }

        public List<Sala> Listar()
        {
            var context = new bdLaboratorioEntities();
            return context.Sala.ToList();
        }

    }
}