//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int qtdComputadores { get; set; }
        public int qtdAlunos { get; set; }
        public bool Projetor { get; set; }
        public string Software1 { get; set; }
        public string Software2 { get; set; }
        public string Software3 { get; set; }
        public string SistemaOperacional { get; set; }
    }
}
